### ISSUE TITLE
create landing page

### ISSUE THREAD

**Issue by holzeis** [bitbetwin/bitbetwin#10]
reference to bitcoins wiki

**Comment by ulrichson** [comment]
Should we integrate the landing page into the current node project, or have a stand-alone version?
I guess it should have a sign-up possibility - how will we collect interessted users?

**Comment by ulrichson** [comment]
I'd suggest to use this template as a starter: http://html5up.net/uploads/demos/overflow/

**Comment by holzeis** [comment]
i would prefer to put it into the node project. by configuration we can switch from productive (landing page) to development (hangman game). - i also like the idea of a beta phase, thus only a chosen group of people can access the beta version of the hangman game. maybe you can include some sort of registration for a beta key on the landing page.?
+1 for the template, looks great

**Comment by bonomat** [comment]
have a look at mailchimp, for the landing page subscription

**Comment by bonomat** [comment]
+1 for template and the integration

**Comment by holzeis** [comment]
for mail service integration - see issue #20
