### ISSUE TITLE
Persistence Layer

### ISSUE THREAD

**Issue by ulrichson** [bitbetwin/bitbetwin#19]
What persistence layer should we use?
At the moment it's only for saving e-mail subscribers.

Possibilities: MongoDB, PostgresSQL, Parse (https://parse.com), ...?

What do you think?

**Comment by holzeis** [comment]
heroku provides a lot of persistence layers...
have a look at https://addons.heroku.com/

**Comment by holzeis** [comment]
+1 for MongoHQ Sandbox

**Comment by holzeis** [comment]
i've added the mongoHQ sandbox in heroku

**Comment by bonomat** [comment]
I would go with a local db for development mode, don't you think so?

**Comment by holzeis** [comment]
yeah, probably a good idea. i'll open an issue for that.
