### ISSUE TITLE
integrate mail service

### ISSUE THREAD

**Issue by holzeis** [bitbetwin/bitbetwin#20]
for now we need to integrate some service for the landing page registration.

this seems like a good option
https://addons.heroku.com/mailgun#starter

https://addons.heroku.com/#email-sms

wdyt?

**Comment by ulrichson** [comment]
I tend to use Mandrill by MailChimp. It has a node.js integration: [https://devcenter.heroku.com/articles/mandrill#using-the-api-with-node-js](https://devcenter.heroku.com/articles/mandrill#using-the-api-with-node-js).
