### ISSUE TITLE
configuration

### ISSUE THREAD

**Issue by holzeis** [bitbetwin/bitbetwin#22]
we need a way to configure different properties like
- mode: productive, beta, development, etc.
- database: local or remote(productive)
- server port
- debugging
  ....

**Comment by bonomat** [comment]
I'm on it ;) you will be able to switch between productive and development via env variables, see
http://stackoverflow.com/questions/8332333/node-js-setting-up-environment-specific-configs-to-be-used-with-everyauth

i'll see if I can push thtat single commit into master soon

**Comment by holzeis** [comment]
nice :+1:

**Comment by bonomat** [comment]
pushed to master

start either with :

NODE_ENV=production coffee server  --> for production mdoe
or
NODE_ENV=development coffee server --> for dev mode

default is dev mode for now
