### ISSUE TITLE
unit tests with mongoose are not working

### ISSUE THREAD

**Issue by bonomat** [bitbetwin/bitbetwin#25]
unfortunately unit tests do not work, see branch #test-bug

**Comment by holzeis** [comment]
do both tests fail or only the e2e test?
i am currently working on the e2e test and it is not finished yet as you can see on the open issue ;)

**Comment by bonomat** [comment]
you didn't had a look at the branch right? only the user test is not working ;)

**Comment by holzeis** [comment]
ups, i thought you meant the master, sorry.
