### ISSUE TITLE
jade

### ISSUE THREAD

**Issue by holzeis** [bitbetwin/bitbetwin#4]
Hey, do we want to use jade?
i had a short look at some examples and it might reduce the amount of writing.
additionally it will increase the readability of the view files see http://jade-lang.com/

Note: jade can be used along with angular.js

**Comment by bonomat** [comment]
+1 for using jade, 
it is kind of "the" standard template engine for nodeJS
further, AKA it will be "compiled" to html on the server side and can then be served to angular

**Comment by ulrichson** [comment]
jade is awesome :)

**Comment by holzeis** [comment]
ok then. i'll open an issue :)
