### ISSUE TITLE
verify email address

### ISSUE THREAD

**Issue by holzeis** [bitbetwin/bitbetwin#41]
user should receive an unique link per email. 
this link should include the hashed email address.
the registration is completed after the email verification.

**Comment by bonomat** [comment]
see branch email-verification
a generation token is generated and stored in db, this activation token should be send to the user after registration

e.g. activate a user : 
http://localhost:8080/activate?token=$2a$10$5Y3PvubOCa0dR5PyflCJhOvba3kZgpLPGU/Huv.uSXjDZfInnbMre#/
