### ISSUE TITLE
login not working anymore

### ISSUE THREAD

**Issue by bonomat** [bitbetwin/bitbetwin#52]
normal login is not working anymore in master -- will be fixed within email-verifaction issue-44

**Comment by bonomat** [comment]
@holzeis did you run the e2e tests after the mass refactoring a few weeks ago? can't find the commit which introduced the bug

**Comment by holzeis** [comment]
hey, i just run the e2e tests and the login works. However, some e2e tests are failing because of #51.

**Comment by bonomat** [comment]
try to clean your database befor starting the server:
console: mongo
use bangmandb
db.users.remove( {})

it can't work with the current code in master since the passwords are
compared in plain text.
i've already fixed it and will push as soon as i have a reliable internet
connection again ;)

**Comment by holzeis** [comment]
how should the login test work, when there is no user in the database?

**Comment by bonomat** [comment]
there is ;)
the problem is that the user in your db might have still the plain text
password and not the encypted one

**Comment by bonomat** [comment]
just delete the old and restart and the login shouldn't work anymore ;)
