### ISSUE TITLE
user login backend

### ISSUE THREAD

**Issue by bonomat** [bitbetwin/bitbetwin#6]
We need a simple user management, i thought about using a btc walled address as first time login, the username can be defined later on.
I did not yet find a single-sign on for that, so we might have to write a login on our own,

i would go with passportjs (https://github.com/jaredhanson/passport) as it is perfectly compatible with express and nodejs

**Comment by holzeis** [comment]
in this context we also need to consider how to handle user sessions. probably an own issue. wdyt?

**Comment by bonomat** [comment]
yes, and actually it also covers part of the db handling, 
i want to make use of mongoose http://mongoosejs.com/
wdyt?

**Comment by holzeis** [comment]
+1
i created an issue for integrating mongoHQ sandbox with mongoosejs in milestone v0.0.2.

**Comment by bonomat** [comment]
great, I'll assign it to me

**Comment by bonomat** [comment]
i'll start a new issue for the sessions as socket.io and passport.js sessions are a bit more complicated to achieve

**Comment by bonomat** [comment]
done in branch login, please review
