### ISSUE TITLE
btc payment

### ISSUE THREAD

**Issue by bonomat** [bitbetwin/bitbetwin#7]
we have to integrate a btc payment provider, i.e. accept payment from users and payout 

i had a look at https://coinbase.com/ as it also provides a node api (https://npmjs.org/search?q=coinbase) 

what do you think?

**Comment by bonomat** [comment]
that also looks promising https://blockchain.info/api/api_receive

**Comment by holzeis** [comment]
good point, but i'll assign this issue to another milestone, maybe v0.0.3? any objections?

**Comment by bonomat** [comment]
that's only the question of which provider shall be used, so v.0.0.2 should be fine, the actual implementation can be in v0.0.3 ;)

**Comment by holzeis** [comment]
yeah propably, but I'd rather deal with the question when it comes to need. then we can evaluate the different providers and their api's for example. otherwise i spend now time on the different provider and have to do the work again when it comes to the integration.

**Comment by holzeis** [comment]
+1 for coinbase. the api gives a nice and smooth impression.
