### ISSUE TITLE
github link in landingpage

### ISSUE THREAD

**Issue by ulrichson** [bitbetwin/bitbetwin#93]
e.g. as done by http://foundation.zurb.com:

![foundation___the_most_advanced_responsive_front-end_framework_from_zurb](https://f.cloud.github.com/assets/449600/1876555/66403a7a-7914-11e3-8fe6-7c74d9014036.png)

**Comment by ulrichson** [comment]
included a github link with 7b0e5d9af6c0e2a9042aed27ebe1281bcac3ebe9

**Comment by bonomat** [comment]
already in master
